server:
  port: 8081
  servlet:
    context-path: /department


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka


management:
  tracing:
    sampling:
      probability: 1.0