server:
  port: 8084
  servlet:
    context-path: /employee


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka


management:
  tracing:
    sampling:
      probability: 1.0